services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp" # DNS
      - "53:53/udp"
      - "8080:80/tcp"
      # - "443:443/tcp" # SSL
      # - "67:67/udp"   # DHCP
      # - "123:123/udp" # NTP
    environment:
      TZ: "Europe/Paris"
      FTLCONF_webserver_api_password: ${PASSWORD}
      FTLCONF_dns_listeningMode: "ALL"
    volumes:
      - './etc:/etc/pihole'
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
