services:
  mariadb:
    image: mariadb:lts
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_PASSWORD=${DB_PW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${DB_USER}

  redis:
    image: redis:alpine
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - redis
      - mariadb
    volumes:
      - ./html:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DB_PW}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_TRUSTED_DOMAINS=${TRUSTED_DOMAIN} nextcloud localhost 127.0.0.1
      - NEXTCLOUD_DEFAULT_PHONE_REGION=FR

  onlyoffice:
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    ports:
      - 9981:80
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}
      - ALLOW_PRIVATE_IP_ADDRESS=true
